// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcFQjsmnbMOOId3hw6iipe84jiAWWBnJM',
    appId: '1:86024798468:web:c4aa758fce858b6361d051',
    messagingSenderId: '86024798468',
    projectId: 'instagram-clone-c98d8',
    authDomain: 'instagram-clone-c98d8.firebaseapp.com',
    storageBucket: 'instagram-clone-c98d8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdz6i33wXdCEd3QjmSeqG8iE34h_o07ZU',
    appId: '1:86024798468:android:c4f71cf71a4f21f861d051',
    messagingSenderId: '86024798468',
    projectId: 'instagram-clone-c98d8',
    storageBucket: 'instagram-clone-c98d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR9fmk2c-tiq2fBEMc5qDqD7v081bYd3M',
    appId: '1:86024798468:ios:35623a963b01ac5a61d051',
    messagingSenderId: '86024798468',
    projectId: 'instagram-clone-c98d8',
    storageBucket: 'instagram-clone-c98d8.appspot.com',
    iosClientId: '86024798468-46pf008h6iq5mumf1c4kmen6rfa3go11.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR9fmk2c-tiq2fBEMc5qDqD7v081bYd3M',
    appId: '1:86024798468:ios:35623a963b01ac5a61d051',
    messagingSenderId: '86024798468',
    projectId: 'instagram-clone-c98d8',
    storageBucket: 'instagram-clone-c98d8.appspot.com',
    iosClientId: '86024798468-46pf008h6iq5mumf1c4kmen6rfa3go11.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
